name: RandomTP
main: com.minersglory.randomtp.RandomTP
version: ${project.version}
api-version: 1.13
commands:
  wild:
    description: Use /wild to be randomly teleported in the wilderness
permissions:
  wild.use:
    description: Allows /wild
    default: op